export enum DirEnum {
    USER_INFO_CERTIFICATE = 'USER_INFO_CERTIFICATE',
    USER_INFO_NATIONAL_CARD = 'USER_INFO_NATIONAL_CARD',
    USER_INFO_NEWSPAPER = 'USER_INFO_NEWSPAPER',
    TicketImage = 'TicketImage',
}
